/**
 * Created by dizl on 2017/2/13.
 */
var busiCode = busiCode || {};
(function(){
    /*********常用的busiCode*********/
    busiCode.common = {
        IMESSINFOFSV_GETMESSINFOCOUNT : "IMESSINFOFSV_GETMESSINFOCOUNT",//获取当前操作员的web消息数量
        IMESSINFOFSV_GETMESSINFO : "IMESSINFOFSV_GETMESSINFO",//获取当前操作员的web消息列表
        IMESSINFOFSV_READMESS:"IMESSINFOFSV_READMESS",//将该消息设置为已读
        ICFGSTATICDATAFSV_GETSTATICDATABYCODETYPE : "ICFGSTATICDATAFSV_GETSTATICDATABYCODETYPE",//根据codeType获取静态数据
        ICFGPROCESSFSV_EDITPROCESS:"ICFGPROCESSFSV_EDITPROCESS",//流程信息编辑
        ICFGPROCESSFSV_QUERYVALIDPROCESSINFO:"ICFGPROCESSFSV_QUERYVALIDPROCESSINFO ",//查询有效的流程数据
        IELECFSV_QUERYCFGELEC: "IELECFSV_QUERYCFGELEC",//查询电子资料
        IELECFSV_GETNEWFILEINPUTID: "IELECFSV_GETNEWFILEINPUTID",//获取新的电子资料输入ID
        IELECFSV_QUERYELECINS:"IELECFSV_QUERYELECINS",//查询电子资料
        ICFGDYNCCOMMONFSV_GETREQUESTURL: "ICFGDYNCCOMMONFSV_GETREQUESTURL",//获取动态表单页面
    };

    /*********权限模块相关的busiCode*********/
    busiCode.sec = {
        ISECFSV_GETSECFUNCTION : "ISECFSV_GETSECFUNCTION",//获取当前操作员的菜单信息
        ISECFSV_ROLEGRANT : "ISECFSV_ROLEGRANT",//角色赋权
        ISECFSV_AUTHOR : "ISECFSV_AUTHOR",//角色赋权
        ISECFSV_OPSTATION : "ISECFSV_OPSTATION",//操作员上岗
        ISECFSV_GETPRIVSBYOPERATORID : "ISECFSV_GETPRIVSBYOPERATORID",//获取当前操作员权限
        ISECFSV_GETBASESTATION : "ISECFSV_GETBASESTATION",//获取操作员默认岗位
        IQUICKSEARCH : "IQUICKSEARCH",//业务：快捷搜索

        ICFGPORTALFSV_GETPORTALBYUSERID:"ICFGPORTALFSV_GETPORTALBYUSERID",//获取当前操作员工作台信息
        ICFGPORTALFSV_LISTSECPORTLET:"ICFGPORTALFSV_LISTSECPORTLET", //获取操作员工作台权限的组件
        ICFGPORTALFSV_SAVEINSPORTLET:"ICFGPORTALFSV_SAVEINSPORTLET", //新增(配置)实例工作台组件
        ICFGPORTALFSV_REMOVESECPORTLET:"ICFGPORTALFSV_REMOVESECPORTLET",//移除(配置)实例工作台组件
        ICFGPORTALFSV_LISTINSPORTLET:"ICFGPORTALFSV_LISTINSPORTLET",//获取操作员该工作台实例已经配置了的组件
        ICFGPORTALFSV_GETINSPORTLETBYID:"ICFGPORTALFSV_GETINSPORTLETBYID",//根据ID获取工作台组件实例信息
        ICFGPORTALFSV_UPDATEINSPORTLETBYID:"ICFGPORTALFSV_UPDATEINSPORTLETBYID",//根据ID修改工作台组件实例 信息
        ICFGPORTALFSV_SAVENEWLAYOUT:"ICFGPORTALFSV_SAVENEWLAYOUT",//布局修改
        ICFGPORTLETFSV_QRYPORTLET:"ICFGPORTLETFSV_QRYPORTLET",//查询工作台组件
        ICFGPORTLETFSV_DELPORTLET:"ICFGPORTLETFSV_DELPORTLET",//删除工作台组件
        ICFGPORTLETFSV_SAVEPORTLET:"ICFGPORTLETFSV_SAVEPORTLET"//保存工作台组件
    };

    /*********客户管理模块相关的busiCode*********/
    busiCode.custMgr = {
        ICFGPRODFSV_GETPRODSPEC:"ICFGPRODFSV_GETPRODSPEC",//查询产品规格信息
        ICFGPRODFSV_GETOFFER:"ICFGPRODFSV_GETOFFER",//查询策划信息
        ICFGPRODFSV_GETOFFEROPER:"ICFGPRODFSV_GETOFFEROPER",//查询策划操作信息
        PT_SH_FS_OI4848:"PT-SH-FS-OI4848",//根据手机号查询成员的信息
        IGROUPMEMBERINFOFSV_DETAILMEMBERINFOBYID:"IGROUPMEMBERINFOFSV_DETAILMEMBERINFOBYID",//集团成员信息详情
        IGROUPMEMBERINFOFSV_ADDMEMBERINFO:"IGROUPMEMBERINFOFSV_ADDMEMBERINFO",//集团成员信息的保存和修改方法
        IACCTINFOFSV_ADDACCOUNTINFO:"IACCTINFOFSV_ADDACCOUNTINFO",//集团账户信息的添加
        IACCTINFOFSV_FINDACCTINFOBYID:"IACCTINFOFSV_FINDACCTINFOBYID",//根据ID查询 集团账户信息
        IACCTINFOFSV_UPDATEACCTINFOBYID:"IACCTINFOFSV_UPDATEACCTINFOBYID",//根据ID更新集团账户信息

    };

    /*********日常任务模块相关的busiCode*********/
    busiCode.routine = {
        /**系统公告**/
        IENBULLETININFOFSV_ADDNOTICEINFO:"IENBULLETININFOFSV_ADDNOTICEINFO",//新增公告内容
        IENBULLETININFOFSV_DELETENOTICE:"IENBULLETININFOFSV_DELETENOTICE",//删除公告
        IENBULLETININFOFSV_UPDATENOTICE:"IENBULLETININFOFSV_UPDATENOTICE",//更新公告
        IENBULLETININFOFSV_QUERYFORNOTICEBYID:"IENBULLETININFOFSV_QUERYFORNOTICEBYID",//根据ID查看公告
        IENBULLETININFOFSV_QUERYFORNOTICEBYPAGE:"IENBULLETININFOFSV_QUERYFORNOTICEBYPAGE",//根据条件查询所有公告信息
        IENBULLETININFOFSV_QUERYBYTYPE:"IENBULLETININFOFSV_QUERYBYTYPE",//根据公告类型进行公告查询
        /**告警**/
        IWARNTYPEDEFINEFSV_DELWARNTYPE : "IWARNTYPEDEFINEFSV_DELWARNTYPE",//告警类型删除
        IWANDEALRULEFSV_DELWARNDEALRULE : "IWANDEALRULEFSV_DELWARNDEALRULE",//告警反馈删除
        IWARNCOLUMNDEFINEFSV_DELWARNCOLUMN : "IWARNCOLUMNDEFINEFSV_DELWARNCOLUMN",//告警字段删除
        IWARNTYPEDEFINEFSV_GETWARNTYPEDEFINE : "IWARNTYPEDEFINEFSV_GETWARNTYPEDEFINE",//查询告警类型信息
        IWARNTYPEDEFINEFSV_UPDATEWARNTYPE : "IWARNTYPEDEFINEFSV_UPDATEWARNTYPE",//修改告警类型
        IWARNCOLUMNDEFINEFSV_GETWARNCOLUMNDEFINE : "IWARNCOLUMNDEFINEFSV_GETWARNCOLUMNDEFINE",//查询告警字段
        IWARNCOLUMNDEFINEFSV_UPDATEWARNCOLUMN : "IWARNCOLUMNDEFINEFSV_UPDATEWARNCOLUMN",//修改告警字段
        IWARNTYPEDEFINEFSV_ADDWARNTYPE : "IWARNTYPEDEFINEFSV_ADDWARNTYPE",//新增告警类型
        IWARNCOLUMNDEFINEFSV_ADDWARNCOLUMN : "IWARNCOLUMNDEFINEFSV_ADDWARNCOLUMN",//新增告警字段
        IWANDEALRULEFSV_GETWARNDEALRULE:"IWANDEALRULEFSV_GETWARNDEALRULE",//获取告警反馈
        IWANDEALRULEFSV_ADDWARNDEALRULE : "IWANDEALRULEFSV_ADDWARNDEALRULE",//新增反馈规则
        IWANDEALRULEFSV_UPDATEWARNDEALRULE : "IWANDEALRULEFSV_UPDATEWARNDEALRULE",//修改反馈规则
        IWARNCOLUMNVALUEFSV_GETWARNDEALBYWARNID :"IWARNCOLUMNVALUEFSV_GETWARNDEALBYWARNID",//根据告警id获取告警详情
        IWARNDEALDETAILFSV_GETDEALDETAIL:"IWARNDEALDETAILFSV_GETDEALDETAIL",//获取告警反馈数据
        IWARNDEALDETAILFSV_ADDDEALDETAIL:"IWARNDEALDETAILFSV_ADDDEALDETAIL",//增加告警反馈数据
        IWANDEALRULEFSV_GETWARNDEALEXT :"IWANDEALRULEFSV_GETWARNDEALEXT",//获取规则及反馈
        IWARNINFOSUM_GETWARNINFOSUM:"IWARNINFOSUM_GETWARNINFOSUM",//告警汇总
        /**收藏夹*/
        IESCOLLECTIONFSV_ADDCOLLECTIONINFO:"IESCOLLECTIONFSV_ADDCOLLECTIONINFO",//添加收藏夹
        IESCOLLECTIONFSV_DELCOLLECTIONINFO:"IESCOLLECTIONFSV_DELCOLLECTIONINFO",//删除收藏夹
        IESCOLLECTIONFSV_QRYCOLLECTIONBYID:"IESCOLLECTIONFSV_QRYCOLLECTIONBYID",//根据主键获取收藏夹信息
        IESCOLLECTIONFSV_QRYCOLLECTIONINFO:"IESCOLLECTIONFSV_QRYCOLLECTIONINFO",//获取收藏夹列表
        /**日常工作流程*/
        IFLOWINSTANCE_STARTFLOW:"IFLOWINSTANCE_STARTFLOW",//启动新流程

        /**商机信息**/
        IBUSIOPPORTINFOFSV_EDITOPPORTINFO:"IBUSIOPPORTINFOFSV_EDITOPPORTINFO",//对商机信息进行编辑
        IBUSIOPPORTINFOFSV_QUERYOPPORTINFO:"IBUSIOPPORTINFOFSV_QUERYOPPORTINFO",//根据查询条件查询商机信息

        /**工作日志*/
        IESWORKLOGFSV_SAVEESWORKLOGINFO:"IESWORKLOGFSV_SAVEESWORKLOGINFO",//工作日志的保存
        IESWORKLOGFSV_QUERYESWORKLOGINFO:"IESWORKLOGFSV_QUERYESWORKLOGINFO",//工作日志的详情

        /**关怀配置*/
        ICFGCARETYPEFSV_UPDATECFGCARETYPEINFO:"ICFGCARETYPEFSV_UPDATECFGCARETYPEINFO",//关怀信息的更新
        ICFGCARETYPEFSV_SAVECFGCARETYPEINFO:"ICFGCARETYPEFSV_SAVECFGCARETYPEINFO",//关怀信息的保存
        ICFGCARETYPEFSV_QUERYCFGCARETYPEINFO:"ICFGCARETYPEFSV_QUERYCFGCARETYPEINFO",//关怀信息的详情
    };


    /*********协议模块相关的busiCode*********/
    busiCode.protocol = {

    };

    /*********营销活动相关的busiCode*********/
    busiCode.ploy = {

    };

    /*********数据分析相关的busiCode*********/
    busiCode.analyze = {

    };

    /*********HTTP相关的busiCode*********/
    busiCode.http = {
        OI3369:"PT-SH-FS-OI3369",//集团详细信息
        OI4814:"PT-SH-FS-OI4814",//集团客户经理信息
        OI4811:"PT-SH-FS-OI4811",//集团产品信息
        OI4578:"PT-SH-FS-OI4578" //集团帐户信息
    };

    /**
     * 其他扩展的busiCode
     * */
    busiCode.other = {
        GET_CURR_USER : PROJECT_URL+"/sec/getCurrUserInfo",//获取当前操作员信息
        GET_USER : PROJECT_URL+"/sec/getUserInfo"   //获取操作员信息
    };
})();